module.exports = {
  title: 'Icons',
  label: 'Icons',
  status: 'ready',
  default: 'all',
  context: {
    icons: [
      'valogo',
      'valogo-clipped',
      'facebook',
      'instagram',
      'pinterest',
      'twitter',
      'youtube',
      'tumblr',
      'googleplus',
      'flickr',
      'tfl',
      'walk',
      'cycle',
      'drive',
      'link',
      'link-external',
      'calendar',
      'clock',
      'ticket',
      'search',
      'download',
      'download-2',
      'mail',
      'phone',
      'signpost',
      'map',
      'pin',
      'price',
      'label',
      'close',
      'close-menu',
      'menu-hamburger',
      'bibliography',
      'bag',
      'fullscreen',
      'plus',
      'plus-thin',
      'minus',
      'minus-thin',
      'quote',
      'interact',
      'listen',
      'watch',
      'pause',
      'view',
      'event-none',
      'point-up',
      'point-right',
      'point-down',
      'point-left',
      'fulltriangle-up',
      'fulltriangle-right',
      'fulltriangle-down',
      'fulltriangle-left',
      'arrow-up',
      'arrow-right',
      'arrow-down',
      'arrow-left',
      'tick-circle'
    ]
  },
  variants: [
    {
      name: 'all',
      label: 'All'
    },
    {
      name: 'social-media',
      label: 'Social media',
      context: {
        icons: [
          'facebook',
          'instagram',
          'pinterest',
          'twitter',
          'youtube',
          'tumblr',
          'googleplus',
          'flickr'
        ]
      }
    },
    {
      name: 'site-icons',
      label: 'Site icons',
      context: {
        icons: [
          'tfl',
          'walk',
          'cycle',
          'drive',
          'link',
          'calendar',
          'clock',
          'ticket',
          'search',
          'download',
          'download-2',
          'phone',
          'signpost',
          'map',
          'pin',
          'price',
          'label',
          'fullscreen',
          'quote',
          'interact',
          'listen',
          'watch',
          'view',
          'pause',
          'event-none'
        ]
      }
    },
    {
      name: 'interface',
      label: 'Interface',
      context: {
        icons: [
          'close',
          'close-menu',
          'menu-hamburger',
          'bag',
          'plus',
          'plus-thin',
          'minus',
          'minus-thin',
          'point-up',
          'point-right',
          'point-down',
          'point-left',
          'fulltriangle-up',
          'fulltriangle-right',
          'fulltriangle-down',
          'fulltriangle-left',
          'arrow-up',
          'arrow-right',
          'arrow-down',
          'arrow-left',
          'tick-circle',
          'link-external'
        ]
      }
    }
  ]
};
