module.exports = {
  title: 'Icons',
  label: 'Icons',
  status: 'ready',
  default: 'all',
  context: {
    icons: [
      'valogo',
      'valogo-clipped',
      'no-img',
      'tiktok',
      'facebook',
      'instagram',
      'pinterest',
      'twitter',
      'youtube',
      'tumblr',
      'googleplus',
      'flickr',
      'tfl',
      'walk',
      'cycle',
      'drive',
      'link',
      'link-external',
      'calendar',
      'clock',
      'ticket',
      'search',
      'download',
      'print',
      'mail',
      'phone',
      'signpost',
      'map',
      'pin',
      'pin-outline',
      'on-display',
      'price',
      'label',
      'close',
      'menu-hamburger',
      'bibliography',
      'bag',
      'fullscreen',
      'plus',
      'minus',
      'quote',
      'interact',
      'listen',
      'watch',
      'pause',
      'shuffle',
      'view',
      'venue',
      'make',
      'event-none',
      'point-up',
      'point-right',
      'point-down',
      'point-left',
      'fulltriangle-up',
      'fulltriangle-right',
      'fulltriangle-down',
      'fulltriangle-left',
      'arrow-up',
      'arrow-right',
      'arrow-down',
      'arrow-left',
      'tick-circle',
      'account',
      'card',
      'gift',
      'shop-bag',
      'tick',
      'delivery',
      'tick-mark',
      'loud',
      'lower-subdued-light',
      'natural-light',
      'person-one',
      'person-one-outline',
      'person-two',
      'person-two-outline',
      'crowded-event',
      'strong-smells',
      'induction-loop',
      'padlock',
      'eye-striked',
      'eye',
      'attention',
      'wordmark-academy',
      'wordmark-americas-foundation',
      'wordmark-directors-circle',
      'wordmark-dundee',
      'wordmark-east-museum',
      'wordmark-east-storehouse',
      'wordmark-east',
      'wordmark-membership',
      'wordmark-patrons',
      'wordmark-publishing',
      'wordmark-shop',
      'wordmark-southken',
      'wordmark-wedgwood',
      'wordmark-young'

    ]
  },
  variants: [
    {
      name: 'all',
      label: 'All'
    },
    {
      name: 'social-media',
      label: 'Social media',
      context: {
        icons: [
          'facebook',
          'instagram',
          'pinterest',
          'twitter',
          'youtube',
          'tumblr',
          'googleplus',
          'flickr',
          'tiktok'
        ]
      }
    },
    {
      name: 'wordmark',
      label: 'Wordmark',
      context: {
        icons: [
          'wordmark-academy',
          'wordmark-americas-foundation',
          'wordmark-directors-circle',
          'wordmark-dundee',
          'wordmark-east-museum',
          'wordmark-east-storehouse',
          'wordmark-east',
          'wordmark-membership',
          'wordmark-patrons',
          'wordmark-publishing',
          'wordmark-shop',
          'wordmark-southken',
          'wordmark-wedgwood',
          'wordmark-young'
        ]
      }
    },
    {
      name: 'css-icons',
      label: 'CSS Icon example',
      context: {
        css_icon_example: true
      }
    }
  ]
};
