module.exports = {
  title: 'Icons',
  label: 'Icons',
  status: 'ready',
  default: 'all',
  context: {
    icons: [
      'valogo',
      'valogo-clipped',
      'facebook',
      'instagram',
      'pinterest',
      'twitter',
      'youtube',
      'tumblr',
      'googleplus',
      'flickr',
      'tfl',
      'walk',
      'cycle',
      'drive',
      'link',
      'link-external',
      'calendar',
      'clock',
      'ticket',
      'search',
      'download',
      'mail',
      'phone',
      'signpost',
      'map',
      'pin',
      'on-display',
      'price',
      'label',
      'close',
      'menu-hamburger',
      'bibliography',
      'bag',
      'fullscreen',
      'plus',
      'minus',
      'quote',
      'interact',
      'listen',
      'watch',
      'pause',
      'view',
      'event-none',
      'point-up',
      'point-right',
      'point-down',
      'point-left',
      'fulltriangle-up',
      'fulltriangle-right',
      'fulltriangle-down',
      'fulltriangle-left',
      'arrow-up',
      'arrow-right',
      'arrow-down',
      'arrow-left',
      'tick-circle',
      'account',
      'card',
      'gift',
      'shop-bag',
      'tick',
      'delivery',
      'tick-mark',
      'person-one',
      'person-two',
      'padlock'
    ]
  },
  variants: [
    {
      name: 'all',
      label: 'All'
    },
    {
      name: 'social-media',
      label: 'Social media',
      context: {
        icons: [
          'facebook',
          'instagram',
          'pinterest',
          'twitter',
          'youtube',
          'tumblr',
          'googleplus',
          'flickr'
        ]
      }
    }
  ]
};
