jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - node-version: '18.1.0'
      - run:
          command: npm run test
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command:
            npm run ci-lint:sass
      - run:
          name: Build static site
          command:
            npm run build
      - run:
          name: Deploy branch to surge.sh
          command:
            ./node_modules/.bin/surge --project www --domain vam-fractal-<<pipeline.git.branch>>.surge.sh

orbs:
  node: circleci/node@5.1.0

version: 2.1

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
